services:
  - type: web
    name: gateway-alumni-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter
    healthCheckPath: /up

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        sync: false

      - key: APP_URL
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false

      - key: SESSION_DOMAIN
        sync: false

      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        value: 5432

      - key: DB_DATABASE
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: SUPER_ADMIN_SEED_PASSWORD
        sync: false

  - type: worker
    name: gateway-alumni-queue
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        value: 5432

      - key: DB_DATABASE
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

  - type: web
    name: gateway-alumni-frontend
    runtime: node
    plan: starter
    rootDir: frontend

    buildCommand: npm install && npm run build

    startCommand: npm run start

    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
